export const FETCH_DATA = 'FETCH_DATA';
export const FETCH_DATA_DECODE = 'FETCH_DATA_DECODE';
export const FETCH_DATA_ENCODE = 'FETCH_DATA_ENCODE';
export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR';
export const POST_DATA_DECODE = 'POST_DATA_DECODE';
export const POST_DATA_ENCODE = 'POST_DATA_ENCODE';